(#12) (#11) (#15);  (#15) -- test-build pipeline workflow update -- adding the codecove stats

diff --git a/.github/workflows/build_microservices.yml b/.github/workflows/build_microservices.yml
--- a/.github/workflows/build_microservices.yml
+++ b/.github/workflows/build_microservices.yml
@@ -43,4 +43,13 @@ jobs:
         if: matrix.test_dir != ''
         run: |
           echo "Running tests in ${{ matrix.test_dir }}"
-          find ${{ matrix.test_dir }} -name '*.csproj' -exec dotnet test {} --no-restore --verbosity normal \; 
+          set -e  # Ensure that the shell exits immediately if any command returns a non-zero status
+          find ${{ matrix.test_dir }} -name '*.csproj' -exec sh -c 'dotnet test "{}" --no-restore --verbosity normal || exit 1' \;
+
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v4.0.1
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          slug: SaintAngeLs/p_software_engineering_2
+          fail_ci_if_error: true
+
